---
- name: get factsse
  hosts: all
  become: true

  tasks:
    - name: Get info
      debug:
        msg: "{{ ansible_mounts }}"
      register: mounts
      
    - name: Get more info
      debug:
        msg: "{{ ansible_hostname }}"
      
      
